# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  release:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Build IT
        run: echo Hello, world!

  DeployDev:
    name: Deploy to Dev
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Dev
      url: https://www.google.com
    steps:
      - name: Deploy
        run: echo Deploy to Dev

  DeployFrontend:
    name: Deploy to Frontend
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Frontend
      url: https://www.google.com
    steps:
      - name: Deploy
        run: echo Deploy to Frontend

  DeployTesting:
    name: Deploy to Testing
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Testing
      url: https://www.google.com
    steps:
      - name: Deploy
        run: echo Deploy to Testing

  ApproveDev:
    name: Approve Dev
    if: github.event.ref == 'refs/heads/main'
    needs: [DeployDev]
    runs-on: ubuntu-latest
    environment:
      name: Dev
    steps:
      - name: Deploy
        run: echo Approving Dev Changes

  DeployQA:
    name: Deploy to QA
    if: github.event.ref == 'refs/heads/main'
    needs: [DeployDev, ApproveDev]
    runs-on: ubuntu-latest
    environment:
      name: QA
      url: https://www.google.com
    steps:
      - name: Deploy
        run: echo Deploy to QA

  ApproveQA:
    name: Approve QA
    if: github.event.ref == 'refs/heads/main'
    needs: [DeployQA]
    runs-on: ubuntu-latest
    environment:
      name: QA
    steps:
      - name: Deploy
        run: echo Approving QA Changes

  DeployWAT:
    name: Deploy to WAT
    if: github.event.ref == 'refs/heads/main'
    needs: [DeployQA, ApproveQA]
    runs-on: ubuntu-latest
    environment:
      name: WAT
      url: https://www.google.com
    steps:
      - name: Deploy
        run: echo Deploy to WAT

  DeployStage:
    name: Deploy to Stage
    if: github.event.ref == 'refs/heads/main'
    needs: [DeployQA, ApproveQA]
    runs-on: ubuntu-latest
    environment:
      name: Stage
      url: https://www.google.com
    steps:
      - name: Deploy
        run: echo Deploy to Stage

  ApproveStage:
    name: Approve Stage
    if: github.event.ref == 'refs/heads/main'
    needs: [DeployStage]
    runs-on: ubuntu-latest
    environment:
      name: Stage
    steps:
      - name: Deploy
        run: echo Approving Stage Changes

  DeployProd:
    name: Deploy to Prod
    if: github.event.ref == 'refs/heads/main'
    needs: [DeployStage, ApproveStage]
    runs-on: ubuntu-latest
    environment:
      name: Prod
      url: https://www.google.com
    steps:
      - name: Deploy
        run: echo Deploy to Prod
    
